import type { BuildTool } from "./types.ts";

export const FUNCTIONAL_TOOLS: BuildTool[] = [
	{
		name: "cabal",
		languages: ["haskell"],
		commands: {
			build: ["cabal build"],
			test: ["cabal test"],
			run: ["cabal run", "cabal run {executable}"],
			install: ["cabal install"],
		},
		lockFiles: ["cabal.freeze"],
		configFiles: ["*.cabal", "cabal.project"],
		linters: ["hlint"],
		formatters: ["ormolu", "stylish-haskell"],
	},
	{
		name: "stack",
		languages: ["haskell"],
		commands: {
			build: ["stack build"],
			test: ["stack test"],
			run: ["stack run", "stack run {executable}"],
			install: ["stack setup", "stack install"],
		},
		lockFiles: ["stack.yaml.lock"],
		configFiles: ["stack.yaml", "package.yaml", "cabal.package-db"],
		linters: ["hlint"],
		formatters: ["ormolu", "stylish-haskell"],
	},
	{
		name: "rebar3",
		languages: ["erlang", "elixir"],
		commands: {
			build: ["rebar3 compile"],
			test: ["rebar3 ct", "rebar3 eunit"],
			run: ["rebar3 shell", "erl"],
			install: ["rebar3 get-deps"],
		},
		lockFiles: ["rebar.lock"],
		configFiles: ["rebar.config", "rebar.config", "mix.exs"],
		linters: ["dialyzer"],
		formatters: [],
	},
	{
		name: "mix",
		languages: ["elixir"],
		commands: {
			build: ["mix compile"],
			test: ["mix test"],
			run: ["mix run", "iex", "iex -S mix"],
			install: ["mix deps.get", "mix deps.install"],
		},
		lockFiles: ["mix.lock"],
		configFiles: ["mix.exs"],
		linters: ["credo", "dialyzer"],
		formatters: ["mix format"],
	},
	{
		name: "swipl",
		languages: ["prolog"],
		commands: {
			build: [],
			test: [],
			run: ["swipl", "swipl -s {file}.pl", 'swipl -g "main,halt"'],
			install: [],
		},
		lockFiles: [],
		configFiles: [],
		linters: [],
		formatters: [],
	},
	{
		name: "sbcl",
		languages: ["lisp", "common-lisp"],
		commands: {
			build: [],
			test: [],
			run: ["sbcl", "sbcl --script {file}.lisp"],
			install: [],
		},
		lockFiles: [],
		configFiles: ["*.asd"],
		linters: [],
		formatters: [],
	},
	{
		name: "clisp",
		languages: ["lisp", "common-lisp"],
		commands: {
			build: [],
			test: [],
			run: ["clisp", "clisp {file}.lisp"],
			install: [],
		},
		lockFiles: [],
		configFiles: [],
		linters: [],
		formatters: [],
	},
];
