import type { BuildTool } from "./types.ts";

export const JAVASCRIPT_TOOLS: BuildTool[] = [
	{
		name: "npm",
		languages: ["javascript", "typescript", "jsx", "tsx"],
		commands: {
			build: ["npm run build", "npm run compile"],
			test: ["npm test", "npm run test"],
			run: ["npm start", "npm run start", "node", "node --loader ts-node/esm"],
			install: ["npm install", "npm ci"],
		},
		lockFiles: ["package-lock.json"],
		configFiles: ["package.json"],
		linters: ["eslint", "eslint --ext .ts,.tsx", "typecheck", "tsc --noEmit"],
		formatters: ["prettier", "prettier --write"],
	},
	{
		name: "yarn",
		languages: ["javascript", "typescript", "jsx", "tsx"],
		commands: {
			build: ["yarn build", "yarn run build"],
			test: ["yarn test", "yarn run test"],
			run: ["yarn start", "yarn run start"],
			install: ["yarn install", "yarn add"],
		},
		lockFiles: ["yarn.lock"],
		configFiles: ["package.json"],
		linters: ["eslint", "yarn lint"],
		formatters: ["prettier", "yarn format"],
	},
	{
		name: "pnpm",
		languages: ["javascript", "typescript", "jsx", "tsx"],
		commands: {
			build: ["pnpm build", "pnpm run build"],
			test: ["pnpm test", "pnpm run test"],
			run: ["pnpm start", "pnpm run start"],
			install: ["pnpm install", "pnpm add"],
		},
		lockFiles: ["pnpm-lock.yaml"],
		configFiles: ["package.json"],
		linters: ["eslint", "pnpm lint"],
		formatters: ["prettier", "pnpm format"],
	},
	{
		name: "bun",
		languages: ["javascript", "typescript", "jsx", "tsx"],
		commands: {
			build: ["bun run build", "bun build"],
			test: ["bun test", "bun run test"],
			run: ["bun run start", "bun run", "node"],
			install: ["bun install", "bun add"],
		},
		lockFiles: ["bun.lockb"],
		configFiles: ["package.json"],
		linters: ["eslint", "bunx eslint", "typescript"],
		formatters: ["prettier", "bunx prettier"],
	},
	{
		name: "deno",
		languages: ["javascript", "typescript", "jsx", "tsx"],
		commands: {
			build: ["deno compile", "deno bundle", "deno task build"],
			test: ["deno test", "deno task test"],
			run: ["deno run", "deno task start", "deno"],
			install: ["deno install", "deno task install"],
		},
		lockFiles: ["deno.lock"],
		configFiles: ["deno.json", "deno.jsonc", "import_map.json"],
		linters: ["deno lint"],
		formatters: ["deno fmt", "deno fmt --"],
	},
	{
		name: "webpack",
		languages: ["javascript", "typescript", "jsx", "tsx"],
		commands: {
			build: ["webpack --mode production", "npx webpack"],
			test: [],
			run: ["webpack serve", "webpack-dev-server"],
			install: [],
		},
		lockFiles: [],
		configFiles: [
			"webpack.config.js",
			"webpack.config.ts",
			"webpack.config.mjs",
		],
		linters: ["eslint-loader"],
		formatters: [],
	},
	{
		name: "vite",
		languages: ["javascript", "typescript", "jsx", "tsx"],
		commands: {
			build: ["vite build", "npx vite build"],
			test: ["vitest"],
			run: ["vite", "vite serve", "npx vite"],
			install: [],
		},
		lockFiles: [],
		configFiles: ["vite.config.js", "vite.config.ts", "vite.config.mts"],
		linters: ["eslint"],
		formatters: ["prettier"],
	},
	{
		name: "rollup",
		languages: ["javascript", "typescript", "jsx", "tsx"],
		commands: {
			build: ["rollup -c", "npx rollup -c"],
			test: [],
			run: ["rollup -c -w"],
			install: [],
		},
		lockFiles: [],
		configFiles: ["rollup.config.js", "rollup.config.ts", "rollup.config.mjs"],
		linters: ["@rollup/plugin-eslint"],
		formatters: ["prettier"],
	},
	{
		name: "esbuild",
		languages: ["javascript", "typescript", "jsx", "tsx"],
		commands: {
			build: ["esbuild", "npx esbuild"],
			test: [],
			run: ["esbuild --watch", "npx esbuild --watch"],
			install: [],
		},
		lockFiles: [],
		configFiles: ["esbuild.config.js", "esbuild.config.mjs"],
		linters: [],
		formatters: [],
	},
];
