import type { BuildTool } from "./types.ts";

export const MISC_TOOLS: BuildTool[] = [
	{
		name: "pub",
		languages: ["dart"],
		commands: {
			build: ["dart build", "flutter build"],
			test: ["dart test", "flutter test"],
			run: ["dart run", "flutter run"],
			install: ["pub get", "flutter pub get"],
		},
		lockFiles: ["pubspec.lock"],
		configFiles: ["pubspec.yaml", "analysis_options.yaml"],
		linters: ["dart analyze", "flutter analyze"],
		formatters: ["dart format", "dart format ."],
	},
	{
		name: "luarocks",
		languages: ["lua"],
		commands: {
			build: ["luarocks make", "lua {file}.lua"],
			test: ["busted", "luacheck"],
			run: ["lua", "luarocks test"],
			install: ["luarocks install"],
		},
		lockFiles: [],
		configFiles: ["*.rockspec"],
		linters: ["luacheck"],
		formatters: [],
	},
	{
		name: "pkg",
		languages: ["julia"],
		commands: {
			build: [],
			test: ["Pkg.test", "julia -e 'using Pkg; Pkg.test(@__MODULE__)'"],
			run: ["julia", "julia {file}.jl"],
			install: ["Pkg.add", "julia -e 'using Pkg; Pkg.add(\"{package}\")'"],
		},
		lockFiles: ["Manifest.toml"],
		configFiles: ["Project.toml"],
		linters: [],
		formatters: [],
	},
	{
		name: "fortran",
		languages: ["fortran"],
		commands: {
			build: ["gfortran", "ifort", "gfortran -o {output}"],
			test: ["gfortran -o test && ./test"],
			run: ["./{executable}", "gfortran -o run && ./run"],
			install: [],
		},
		lockFiles: [],
		configFiles: [],
		linters: ["gfortran -Wall", "gfortran -std=f2008"],
		formatters: [],
	},
	{
		name: "nasm",
		languages: ["assembly", "asm"],
		commands: {
			build: ["nasm -f elf64", "nasm -f macho64", "as"],
			test: [],
			run: ["ld -o {output} && ./{output}", "./{executable}"],
			install: [],
		},
		lockFiles: [],
		configFiles: [],
		linters: [],
		formatters: [],
	},
	{
		name: "as",
		languages: ["assembly", "asm"],
		commands: {
			build: ["as -o {output}", "gcc -c"],
			test: [],
			run: ["ld -o {output} && ./{output}"],
			install: [],
		},
		lockFiles: [],
		configFiles: [],
		linters: [],
		formatters: [],
	},
	{
		name: "gnatmake",
		languages: ["ada"],
		commands: {
			build: ["gnatmake", "gnatmake -o {output}"],
			test: [],
			run: ["./{executable}"],
			install: [],
		},
		lockFiles: [],
		configFiles: ["*.adb", "*.ads", "gnat.adc"],
		linters: [],
		formatters: [],
	},
	{
		name: "vbc",
		languages: ["vb", "visual-basic"],
		commands: {
			build: ["vbc", "vbc /target:exe", "MSBuild"],
			test: [],
			run: ["{executable}.exe"],
			install: [],
		},
		lockFiles: [],
		configFiles: ["*.vb", "*.vbproj", "*.sln"],
		linters: ["StyleCop"],
		formatters: [],
	},
	{
		name: "packrat",
		languages: ["r"],
		commands: {
			build: [],
			test: [],
			run: ["Rscript", "R -f {file}.R", "R"],
			install: ["packrat::install.packages", "renv::install"],
		},
		lockFiles: ["packrat.lock"],
		configFiles: ["DESCRIPTION", "renv.lock"],
		linters: ["lintr"],
		formatters: [],
	},
	{
		name: "renv",
		languages: ["r"],
		commands: {
			build: [],
			test: [],
			run: ["Rscript", "R"],
			install: ["renv::install", "install.packages"],
		},
		lockFiles: ["renv.lock"],
		configFiles: ["DESCRIPTION", ".Rprofile"],
		linters: ["lintr"],
		formatters: [],
	},
	{
		name: "sql",
		languages: ["sql"],
		commands: {
			build: [],
			test: [],
			run: ["psql", "mysql", "sqlite3"],
			install: [],
		},
		lockFiles: [],
		configFiles: ["*.sql"],
		linters: ["sql-lint", "pgFormatter"],
		formatters: ["pgFormatter", "sqlformat"],
	},
	{
		name: "dcc",
		languages: ["pascal", "delphi"],
		commands: {
			build: ["dcc32", "dcc64", "msbuild"],
			test: [],
			run: ["{executable}.exe"],
			install: [],
		},
		lockFiles: [],
		configFiles: ["*.dpr", "*.dpk", "*.dproj"],
		linters: [],
		formatters: [],
	},
	{
		name: "zig",
		languages: ["zig"],
		commands: {
			build: ["zig build", "zig build-exe"],
			test: ["zig test"],
			run: ["zig run", "zig run {file}.zig"],
			install: [],
		},
		lockFiles: [],
		configFiles: ["build.zig", "zig.mod"],
		linters: [],
		formatters: ["zig fmt"],
	},
	{
		name: "perl",
		languages: ["perl"],
		commands: {
			build: ["perl Makefile.PL", "dzil build"],
			test: ["prove", "perl -I lib -MTest::More"],
			run: ["perl", "perl {file}.pl"],
			install: ["cpanm", "cpan"],
		},
		lockFiles: [],
		configFiles: ["Makefile.PL", "Build.PL", "cpanfile", "dist.ini"],
		linters: ["perlcritic"],
		formatters: ["perltidy"],
	},
];
